/**
 * Case assembly. Given a transaction, produce the evidence bundle, the
 * analyst-facing summary, and the SAR first draft.
 *
 * These are template-driven on purpose: a real deployment would call an LLM
 * here, and the shape of the response is what the client renders either way.
 */

import { HIGH_RISK_COUNTRIES } from '../seed.mjs';
import { riskLabel, scoreTransaction, SAR_THRESHOLD } from './scoring.mjs';

function isHighRiskLocation(location) {
  return HIGH_RISK_COUNTRIES.some((country) => country.code === location || country.name === location);
}

const money = (t) => `${t.currency} ${Number(t.amount).toLocaleString()}`;
const pct = (t) => `${(t.riskScore * 100).toFixed(0)}%`;

function jurisdictionNote(location) {
  return isHighRiskLocation(location)
    ? `${location} is on the elevated-risk jurisdiction watchlist`
    : `${location} is not currently watchlisted, but the pattern is atypical for this corridor`;
}

function indicators(t) {
  const { factors } = scoreTransaction(t);
  const lines = factors.map((f) => `• ${f.detail} (+${(f.weight * 100).toFixed(0)} pts)`);

  // Seeded transactions carry a stored model score that includes signals the
  // rule engine can't see (graph network, customer-profile drift). Show the
  // remainder explicitly rather than letting the arithmetic look broken.
  const ruleTotal = factors.reduce((s, f) => s + f.weight, 0);
  const remainder = Math.round((t.riskScore - Math.min(ruleTotal, 1)) * 100);
  if (remainder >= 3) {
    lines.push(
      `• Model overlay contributes a further +${remainder} pts from graph-network and customer-profile signals`
    );
  }

  lines.push(`• Composite score ${pct(t)} against a ${SAR_THRESHOLD * 100}% review threshold`);
  return lines.join('\n');
}

export function buildEvidence(t, allTransactions) {
  const related = allTransactions.filter(
    (o) => o.id !== t.id && (o.customerId === t.customerId || o.location === t.location)
  );

  return [
    {
      source: 'Transaction ledger',
      status: 'retrieved',
      detail: `${t.id} — ${money(t)} via ${t.channel} from ${t.location}`,
    },
    {
      source: 'Customer profile (KYC)',
      status: 'retrieved',
      detail: `${t.customer} · ${t.customerId} · profile last refreshed 14 months ago`,
    },
    {
      source: 'Related activity',
      status: related.length ? 'retrieved' : 'empty',
      detail: related.length
        ? `${related.length} transaction(s) share this customer or corridor: ${related
            .slice(0, 4)
            .map((r) => r.id)
            .join(', ')}`
        : 'No other ledger activity matches this customer or corridor',
    },
    {
      source: 'Policy library',
      status: 'retrieved',
      detail: `Matched typology guidance for "${t.type}" and jurisdiction rules for ${t.location}`,
    },
    {
      source: 'Sanctions & PEP screening',
      status: isHighRiskLocation(t.location) ? 'attention' : 'clear',
      detail: jurisdictionNote(t.location),
    },
  ];
}

export function buildSummary(t) {
  return `CASE ANALYSIS — ${t.id}

${t.customer} moved ${money(t)} through the ${t.channel} channel from ${t.location}. The scoring engine rated this ${pct(t)} (${riskLabel(t.riskScore)}), classified as ${t.type}.

WHY IT SCORED THIS WAY
${indicators(t)}

SUGGESTED NEXT STEPS
1. Pull the full 90-day transaction history for ${t.customerId}
2. Verify source of funds and the stated purpose of the transfer
3. Check for related accounts moving similar amounts through ${t.location}
4. Decide whether a SAR filing is warranted and record the reasoning below

Generated by the case assembly service. An investigator must review and sign off before anything is filed.`;
}

export function buildSarDraft(t) {
  return `SUSPICIOUS ACTIVITY REPORT — DRAFT

SUBJECT: ${t.customer} (ID: ${t.customerId})
TRANSACTION: ${t.id} | ${money(t)} | ${t.channel} | ${t.location}
TYPOLOGY: ${t.type}
RISK SCORE: ${pct(t)} (${riskLabel(t.riskScore)})

BACKGROUND
${t.customer} conducted a transaction of ${money(t)} via the ${t.channel} channel originating from ${t.location}. The transaction was scored at ${pct(t)}, which exceeds the ${SAR_THRESHOLD * 100}% threshold for review.

DESCRIPTION OF SUSPICIOUS ACTIVITY
The combination of transaction amount (${money(t)}), origin jurisdiction (${t.location}) and channel (${t.channel}) is consistent with the ${t.type} typology. ${jurisdictionNote(t.location)}.

PARTIES INVOLVED
Primary subject: ${t.customer} (Customer ID: ${t.customerId})
Origin: ${t.location}
Channel: ${t.channel}
Amount: ${money(t)}

INDICATORS
${indicators(t)}

CONCLUSION AND RECOMMENDED ACTION
On the indicators above, filing a SAR is recommended. The investigator should review all account activity for the preceding 180 days and complete enhanced due diligence on ${t.customer}.

DRAFT — REQUIRES COMPLIANCE OFFICER REVIEW AND APPROVAL BEFORE FILING`;
}

export function buildCase(t, allTransactions) {
  return {
    transactionId: t.id,
    assembledAt: new Date().toISOString(),
    evidence: buildEvidence(t, allTransactions),
    summary: buildSummary(t),
    sarDraft: buildSarDraft(t),
    factors: scoreTransaction(t).factors,
  };
}
